### ISSUE TITLE
Some guidance please...

### ISSUE THREAD

**Issue by dimpol** [K2/Scripting#3]
Hello,
I tried to run Test-AllVirtualMemory both locally and against a domain joined machine. But I am getting:

ResultList ResultDictionary ExecutionTime
---------- ---------------- -------------
{}

I am really interested in your detection approach. Would you be so kind as to provide me with a very brief tutorial on how to start using you code? (I went through the source code comments already...)

Thank you in advance.

**Comment by K2** [comment]
did you get it going ? this is closed now? I'll get some more examples on the wiki, I setup a couple test domains here.

**Comment by dimpol** [comment]
@K2 I was stupid enough to not understand that there is a hash server I should setup first. I am trying to get the HashServer going as we speak....
